name: lru_cache
homepage: https://shtanko.dev
description: >-
  a simple least recently used (LRU) cache implementation in dart.
version: 0.0.2
repository: https://github.com/ashtanko/lru_cache

topics:
  - lru-cache
  - cache
  - caching

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  synchronized: ^3.4.0

dev_dependencies:
  lint: ^2.8.0
  test: ^1.31.1
