name: lru_cache
homepage: https://shtanko.dev
description: >-
  a simple least recently used (LRU) cache implementation in dart.
version: 0.0.2
repository: https://github.com/ashtanko/lru_cache

topics:
  - lru-cache
  - cache
  - caching

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  synchronized: ^3.3.0+3

dev_dependencies:
  lint: '>=1.5.0 <3.0.0'
  test: ^1.16.4
